App translate10 - home page fr
lebalz/events-app pull request #63
Opened 2024-06-30 10:03 UTC by zerifah

2024-06-30 10:05 UTC, zerifah commented
The video is on Teams

2024-07-01 06:35 UTC, zerifah commented
I've add the videos. I don't have do a new PR, it's ok? (It would be take the new commit?)

2024-07-01 08:51 UTC, lebalz requested changes

2024-07-01 08:51 UTC, lebalz commented on src/pages/index.tsx
>                          <div className="card" style={{ boxShadow: 'var(--ifm-global-shadow-md)' }}>
```suggestion
                        <div className="card" style={{ boxShadow: 'var(--ifm-global-shadow-md)' }}>
                          <div className="card__header">
                                <h2>Phase d'introduction</h2>
                            </div>
                            <div className="card__body">
                                Le calendrier est encore dans sa phase d'introduction. Des retours peuvent être transmis
                                grâce à l'application de traçage de bugs (voir Video).
                                <h3>Merci beaucoup pour votre aide.</h3>
                            </div>
```

2024-07-01 08:51 UTC, lebalz commented on src/pages/index.tsx
>                          <div className="card" style={{ boxShadow: 'var(--ifm-global-shadow-md)' }}>
i'd keep this section to make sure users are aware of tha fact that the calendar is still in a introductory phase...

2024-07-02 07:15 UTC, lebalz approved these changes

2024-07-02 07:15 UTC, merged